name: Build Android APK

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y \
            git zip unzip openjdk-17-jdk wget \
            autoconf automake libtool pkg-config \
            zlib1g-dev libncurses5-dev libncursesw5-dev \
            libtinfo5 cmake libffi-dev libssl-dev \
            build-essential ccache libltdl-dev \
            python3-pip python3-dev python3-setuptools
          
          # Install newer autoconf
          wget http://ftp.gnu.org/gnu/autoconf/autoconf-2.72.tar.gz
          tar -xzf autoconf-2.72.tar.gz
          cd autoconf-2.72
          ./configure && make && sudo make install
          cd ..

      - name: Install Python dependencies
        run: |
          pip install --upgrade pip
          pip install buildozer cython

      - name: Cache Buildozer
        uses: actions/cache@v3
        with:
          path: |
            .buildozer
          key: ${{ runner.os }}-buildozer-${{ hashFiles('buildozer.spec') }}

      - name: Build with Buildozer
        run: buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MaelToDo-debug
          path: bin/*.apk